### ISSUE TITLE
你好问下使用问题

### ISSUE THREAD

**Issue by a464679590** [asss-whom/QidianCrawler#1]
如果出现FileNotFoundError，请对照[🌏 准备工作 | DrissionPage](https://g1879.gitee.io/drissionpagedocs/get_start/before_start)解决。
这个说明网站无法打开，可不可以重新发一下谢谢了，我现在就是提示这个错误说明是要进行手动配置。

**Comment by a464679590** [comment]
FileNotFoundError: 无法找到浏览器可执行文件路径，请手动配置。
 提示是这个，说明网页打开提示bad gateway

**Comment by a464679590** [comment]
解决了，先试试能不能下载VIP章节，大佬有没有做过废卢的下载脚本

**Comment by asss-whom** [comment]
您好，原先提供的网址链接已被修正至正确的状态。
我没有做过飞卢的下载脚本，但是这些脚本的原理都是一样的。
它们的大致原理都是找到小说的所有章节的URL => 同步/并行的下载所有URL => 使用re/Xpath/CSS Selector提取正文 => 保存。
衷心希望我的回复能对您有所帮助。

**Comment by a464679590** [comment]
好的谢谢了大佬
