### ISSUE TITLE
VIP章节下载问题

### ISSUE THREAD

**Issue by a464679590** [asss-whom/QidianCrawler#2]
下载时候网页有时候会直接加载不出来下载失败，然后下载VIP章节前一部分没啥问题，到后边全是乱码，感觉是触发了起点的防盗机制？

**Comment by asss-whom** [comment]
1. 关于下载失败问题：为了解决这一问题，建议您参考[⚙️ 配置文件的使用 | DrissionPage官网](https://www.drissionpage.cn/advance/ini)的指南。您可以创建一个新的.ini文件，并在[other]部分调整retry_times和retry_interval的参数设置。也可以直接编辑main.py文件中的第42行，将self.page.get(url)语句修改为self.page.get(url, retry=[int], interval=[float])，并填入合适的重试次数和间隔。
2. 关于乱码问题：这应当是由于起点的防盗机制所导致的。您可以尝试调整main.py文件中第37行的sleep语句的等待时间，但不一定有用。

**Comment by asss-whom** [comment]
我不知道你改没改sleep语句，我刚才自己试着跑了一下，确实慢的我难以接受😂
以我的经验来看，访问太快起点一般都要乱码，有时候还要弹出验证码，这个速度只有靠自己掌控了😉

**Comment by a464679590** [comment]
我没改sleep，不过就算这种速度我在下载一百多章的时候也出现了滑动验证码，感觉就是在验证之后的章节开始变成了乱码要是下载速度改快点说不定起点能把账号给ban了。还有就是我中午试的挂着下载的时候有时候会卡死，就是显示的下载进度不动了页面也不会自动切换了，然后下一回下载100章左右时候也是进度条不动了但是还能自动切换页面到最后也成功下载了，等今晚我回去按你说的方法试试能不能解决下载失败的问题。

**Comment by asss-whom** [comment]
请问一下卡死之后Console有报错吗，类似于不能连接上浏览器之类的？另外下载进度不动一般是多久，有没有超过11秒？理论上11秒以内都算正常值。
如果这种卡死的状况一直发生，我会试着添加一个分章节下载的功能，它可以避免重复下载已经下载却没有存储的内容。
另外我会修改程序，避免报错之后之前的所有下载都丢失掉，并告知保存了多少章节。

**Comment by a464679590** [comment]
没有报错，浏览器一切正常，单纯就是进度条不动了和那个预计时间不显示了、页面也不会自动切换了，然后我等了五六分钟也都还是不会动只能重新开启下载。
分章节下载的功能功能感觉很有必要，今天中午就是卡死了一下挂了三四十分钟等于说白挂了啥都没下载下来，然后后续下载更新的章节也不需要从新再下载了，这样会方便很多。
再说下这个工具真的是对我这样看后宫书的人很有必要，有些书我一直买屯了好多章想着等等再看，结果等看的时候发现书被封掉了，碰到过好多次这种情况了都正常买的书结果没看多少就封了实在是好气人，用这个工具至少可以保存下来备份即使说书后来被封了也还能看到买过的章节，至少不至于买书的钱打水漂了。
再次感谢下大佬的工具，那我就等你更新下个版本了，更新完我再使用使用说说体验。

**Comment by asss-whom** [comment]
版本已更新，可以保存与自动跳过已下载章节了。我还在思考是否要加入分章节下载，这个功能不知道怎么实现最适合。

**Comment by a464679590** [comment]
有个思路就是选择分章下载的话就是先输入书页地址，然后输入起始那一章节的地址，在输入最终章节的地址，就相当于选中了那个区间一样，一个是起始一个是结束。

**Comment by asss-whom** [comment]
主要是分章节的话是一个区间的保存到一个文件上，还是一个章节一个文件。

**Comment by a464679590** [comment]
最好就是按顺序保存到一个txt文件上，这样合并资源也方便，不然是一个个的txt有可能会出现乱序情况会很麻烦。

**Comment by asss-whom** [comment]
中，我明天看看怎么搞最好。今天这个版本太丑陋了😂。

**Comment by a464679590** [comment]
行，谢谢了能用就行，我前天还有本书没看被封了气死了，有这个存档起来方便多了。

**Comment by asss-whom** [comment]
按范围下载的功能已添加。

**Comment by a464679590** [comment]
好的谢谢，我晚上回家试试

**Comment by a464679590** [comment]
我简单用了下分章下载的功能，用着正常没出啥问题我试着下载了二三十章，就是选择章节那里有点不方便因为是按序号选择上下限的，使用着没有问题但是往往小说中会插入一些通知章节或者是其他一些活动章节，所以说按照原文章节比如说是66章到99章的话填入-U 66 -L 99的话往往得到的章节并不是想到的第66章到99章。
还有就是我测试出来的比如说要下载第1、2两张，我输入范围是1 2，但是正常情况下只会出现第二张第一章没有下载，必须要输入0 2 才能下载这两章。

**Comment by asss-whom** [comment]
> 还有就是我测试出来的比如说要下载第1、2两张，我输入范围是1 2，但是正常情况下只会出现第二张第一章没有下载，必须要输入0 2 才能下载这两章。

已修改，现在你可以使用`-l 1 -u 2`来下载1~2章了。

> 所以说按照原文章节比如说是66章到99章的话填入-U 66 -L 99的话往往得到的章节并不是想到的第66章到99章。

这个问题不太容易修改，因为这个程序是索引所有章节URL的列表来分章节下载的。你有没有使章节数正确的想法？
我的想法：
1. 按序号输出所有的章节。这样序号是正确的，但是会打印很多行，并且也不太容易找到你想要的章节；
2. 用正则过滤，只保留有”第(.*?)章“格式的章节。但是这样的话有些正常的章节就会漏掉，并且这也无法应对作者自己把章节序号打重复的情况。

**Comment by a464679590** [comment]
显示序号的话章节一多确实就该很乱了，正则的话也有可能漏章节。那不如就这样了，不是啥大问题，只要现在按序号下载不会再漏下载就好，输入的序号大不了多试几下找出所需的就好了。

**Comment by asss-whom** [comment]
👌，那我就关issue了。

**Comment by a464679590** [comment]
这几天使用下来发现个规律，这个起点下载出现乱码貌似不是触发了防盗机制，而是最近一个月之内的所有章节下载下来都是加密字。

**Comment by asss-whom** [comment]
在浏览器上看到的也是加密的字体吗？如果不是的话，就是起点采用了字体加密，不然的话就是你的账号被标记了。

**Comment by asss-whom** [comment]
那应该是字体加密了，你可以试试用fontTools库来破解，参见[起点小说字体加密python TTFont解析流_python ttfont解析字体-CSDN博客](https://blog.csdn.net/weixin_41804512/article/details/108871124)。

**Comment by asss-whom** [comment]
你能在新的issue下面提供更多的信息吗？比如你看的小说名字，出现乱码的章节数等等…
