### ISSUE TITLE
破解起点字体加密

### ISSUE THREAD

**Issue by asss-whom** [asss-whom/QidianCrawler#3]
破解起点的字体加密，避免下载乱码。

**Comment by a464679590** [comment]
就比如说死灵法师在未世疯狂中兵，这本书。从408章这章是4月24号发布的提取都是加密文字，在408章之后的章节我随机挑选了几张提取也都是乱码。但是407之前是4月23号发布的这之前包括这章都可以正常提取。
再比如说东京：被太太觊舰的我只想做游戏，这本同样有这种情况222章是4月24发布的，这之后包括这章的我随机挑选几张都是加密文字，在这之前的章节都正常。
所以我觉得可能是起点在一个月之内的章节都对文字进行了加密，所以提取出来都是加密文字。

**Comment by asss-whom** [comment]
我没有订阅这些章节。
我需要您的帮忙，请您随机抽一乱码章节 => 按下`Ctrl + U`查看源代码 => 右键将其保存 => 粘贴至这个issue。
这对我分析起点的加密有很大的帮助。

**Comment by a464679590** [comment]
[view-source_https___www.qidian.com_chapter_1038494091_790495906_.zip](https://github.com/asss-whom/QidianCrawler/files/15436169/view-source_https___www.qidian.com_chapter_1038494091_790495906_.zip)
不能直接发html我打包一下，这个是东京：被太太觊觎的我只想做游戏，第222章4月24发布的，我现在又试了一下还是4月24以后章节都是加密的，4月23日发布的221章可以正常提取。

**Comment by a464679590** [comment]
要是还需要其他的给我说我再给你发，这几本我都是全订了

**Comment by asss-whom** [comment]
我看了，确实是字体反爬，你这篇文章使用的字体已在附件[fixed.lwkgxe7f.zip](https://github.com/asss-whom/QidianCrawler/files/15436365/fixed.lwkgxe7f.zip)。
解决字体反爬不是一件容易的事，并且大部分的起点文章都没有采用字体反爬。
我也只是一个业余人士，我可能帮不上您的忙了。
你可以试试`tesseract`等OCR库，网页截图可以参见[🚤 截图和录像 | DrissionPage官网](https://www.drissionpage.cn/ChromiumPage/screen/)。

**Comment by a464679590** [comment]
好的没事，感谢了
